# Generated by Django 3.1.5 on 2021-03-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instagram_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('private', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=400)),
                ('follower', models.IntegerField()),
                ('following', models.IntegerField()),
                ('posts', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
