# Generated by Django 3.1.5 on 2021-04-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeforces_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('handle', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('reg_time', models.CharField(max_length=200)),
                ('last_online', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('max_rank', models.IntegerField()),
                ('friends', models.IntegerField()),
                ('rating', models.CharField(max_length=200)),
                ('max_rating', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
