# Generated by Django 3.1.5 on 2021-04-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_codeforces_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='github_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('public_repos', models.IntegerField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
