# Generated by Django 3.1.5 on 2021-04-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_twitter_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter_data',
            old_name='screem_name',
            new_name='screen_name',
        ),
    ]
