# Generated by Django 3.1.7 on 2021-04-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210401_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeforces_data',
            name='city',
        ),
        migrations.RemoveField(
            model_name='codeforces_data',
            name='country',
        ),
        migrations.RemoveField(
            model_name='codeforces_data',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='codeforces_data',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='codeforces_data',
            name='max_rank',
        ),
        migrations.RemoveField(
            model_name='codeforces_data',
            name='max_rating',
        ),
        migrations.RemoveField(
            model_name='codeforces_data',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='codeforces_data',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='codeforces_data',
            name='rating',
        ),
    ]
