# Generated by Django 3.1.7 on 2021-04-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210401_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeforces_data',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='codeforces_data',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='codeforces_data',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='codeforces_data',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='codeforces_data',
            name='max_rank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='codeforces_data',
            name='max_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='codeforces_data',
            name='organisation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='codeforces_data',
            name='rank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='codeforces_data',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='codeforces_data',
            name='friends',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='codeforces_data',
            name='handle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='codeforces_data',
            name='last_online',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='codeforces_data',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='codeforces_data',
            name='reg_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
