# Generated by Django 3.1.5 on 2021-04-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_reddit_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reddit_data',
            name='public_description',
        ),
    ]
