# Generated by Django 3.1.5 on 2021-04-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_reddit_data_public_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reddit_data',
            name='display_name',
        ),
    ]
