# Generated by Django 3.1.5 on 2021-04-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_reddit_data_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reddit_data',
            name='is_gold',
        ),
        migrations.RemoveField(
            model_name='reddit_data',
            name='verified',
        ),
    ]
